// <auto-generated />
namespace JumpFocus.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class MoveMugshot : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MoveMugshot));
        
        string IMigrationMetadata.Id
        {
            get { return "201408191908582_Move Mugshot"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
